name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-265.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  intl: ^0.17.0 # Downgraded for compatibility with charts_flutter
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0

dependency_overrides:
  image_picker_for_web: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/logo.jpg
    - Assets/google_icon.png
    - Assets/facebook_icon.png
    - Assets/men_shoes.jpg
    - Assets/menjacket.jpg
    - Assets/unisexcap.jpg
    - Assets/unisexhoodie.jpg
    - Assets/womenblouses.jpg
    - Assets/womendress.jpg
    - Assets/jt.png
    - Assets/spx.png
    - Assets/bob.jpg
    - Assets/david.jpg
    - Assets/dresscream.jpg
    - Assets/dresspink.jpg
    - Assets/shoe.jpg
    - Assets/slipper.jpg
    - Assets/mpants1.jpg
    - Assets/mpants2.jpg
    - Assets/mshirt2.jpg
    - Assets/mshort1.jpg
    - Assets/uncap1.jpg
    - Assets/unjacket1.jpg
    - Assets/unshoes1.jpg
    - Assets/untshirt1.jpg
    - Assets/wmcroptop1.jpg
    - Assets/wmcroptop2.jpg
    - Assets/wmdenim1.jpg
    - Assets/wmdress1.jpg
